### ISSUE TITLE
print needs parentheses?

### ISSUE THREAD

**Issue by nauticus25** [kk7ds/pynx584#1]
I'm running this on a v1 RPi B, latest Raspian Jessie with the intention of interfacing my Caddx with Home-Assistant.  I'm not sure I have the nx584 programmed correctly yet, but that's another issue.  I'm also newish to Python, so apologies for any newbie errors on my part.  When I run nx584_client after starting nx584_server, I get the following error:

`File "/usr/local/bin/nx584_client", line 138`
    `print event`
                `^`
`SyntaxError: Missing parentheses in call to 'print'`

I changed it to 

`print(event)`

and ran it again.  This time I got

`File "/usr/local/bin/nx584_client", line 142`
 `print clnt.get_version()`
   `^`
`SyntaxError: invalid syntax`

So I changed it to

`print(clnt.get_version())'

and that seemed to work.  I get 

`+------+------+--------+--------+`
`| Zone | Name | Bypass | Status |`
`+------+------+--------+--------+`
`+------+------+--------+--------+`

as the result, but I'm assuming it's empty because I don't have the nx584 configured correctly.

**Comment by kk7ds** [comment]
Yep, I fixed this in kk7ds/pynx584@7f1cb90e1d0f1dfb943705e7407407ef52931f93

I assume you see this because you installed from pip?

**Comment by nauticus25** [comment]
Yes.  Sorry, I'm a bit new to linux and github.  I installed with `sudo pip3 install pynx584`.  Running that without sudo gave me some write errors.

**Comment by kk7ds** [comment]
I just pushed 0.3 which should include that. Do this to get it:

```
# sudo pip3 install -U pynx584
```

**Comment by nauticus25** [comment]
Awesome, thank you!  That worked.  Well, it didn't error out, at least.  I need to figure out the programming of the nx584.  Do you have a reference of the location 72 programming required for the nx584 serial connection?  I've tried a couple of different ways and am getting some errors when I run nx584_server.

**Comment by kk7ds** [comment]
Hmm, which panel do you have? location 72 on the NX8 is not related to this...

**Comment by nauticus25** [comment]
I have an NX8E which has a serial port on-board, but I also have the nx584 module and am using the serial connection from that to the RPi.  In the nx584 manual, 72 is the address of the module.  Sorry, maybe I should have said "address 72" before instead of "location".

**Comment by kk7ds** [comment]
Hmm, I guess I never thought of using a 584 with an 8E. I guess if you disable it in location 207 then maybe it'll work. Even still, unless you know it will work, I'd try directly connected to the 8E's port if there is any question.

If you run the server with --debug you should see it try to talk to the thing over the serial port. That's how I'd check that it's working at a low-level.

**Comment by nauticus25** [comment]
Yeah, I didn't do enough research when I got it almost 10 years ago and assumed I'd need the 584.  Oh well.  I just found the configuration for [https://github.com/tjko/nxgipd](url) and will try that now.  I'll make sure location 207 is disabled.  I'm actually using a Sabrent serial to USB adapter with a FTDI chipset, which makes this even more of a hack, I guess.  Perhaps I may just have to wire it up manually.  Thanks for your quick assistance!

**Comment by kk7ds** [comment]
Yeah, so the way I do it is I have one of these at the panel:

http://www.amazon.com/ONETAK-Ethernet-Converter-Adapter-Adaptor/dp/B00ATV2DX2?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_search_detailpage

So that I can connect to it over the network and not need a pi or something else right there. A Pi will work fine too of course.

Anyway, good luck with it. I'm going to close this issue since the original thing is fixed. Feel free to open another if you find anything else or have trouble getting it to talk. You can also email me directly if you have other panel-programming-related issues.
