### ISSUE TITLE
Date/Time Errors in Log

### ISSUE THREAD

**Issue by Pre10der** [kk7ds/pynx584#10]
I am receiving these errors in my log:

> 2017-12-08 12:03:09,797 main INFO Ready
> 2017-12-08 12:03:09,957 controller INFO Loaded extensions []
> 2017-12-08 12:03:10,304 _internal INFO  * Running on http://192.168.x.x:5007/ (Press CTRL+C to quit)
> 2017-12-08 12:03:11,964 controller ERROR System asserts Box tamper
> 2017-12-08 12:03:11,971 controller INFO System asserts Valid partition 1
> 2017-12-08 12:03:11,979 controller INFO System asserts Timing a high voltage battery change
> 2017-12-08 12:03:11,988 controller INFO System asserts Loss of system time
> 2017-12-08 12:03:11,997 controller INFO System asserts AC power on
> 2017-12-08 12:03:12,287 controller INFO System de-asserts Loss of system time
> 2017-12-08 12:03:14,387 controller ERROR Failed to process message type 10
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/nx584/controller.py", line 599, in controller_loop
>     getattr(self, name)(frame)
>   File "/usr/local/lib/python3.4/dist-packages/nx584/controller.py", line 519, in process_msg_10
>     hour=hour, minute=minute)
> ValueError: month must be in 1..12
> 2017-12-08 12:03:16,004 controller ERROR Failed to process message type 10
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/nx584/controller.py", line 599, in controller_loop
>     getattr(self, name)(frame)
>   File "/usr/local/lib/python3.4/dist-packages/nx584/controller.py", line 519, in process_msg_10
>     hour=hour, minute=minute)
> ValueError: month must be in 1..12

Is curious to know if this is related to US date format in an AU time zone?

**Comment by kk7ds** [comment]
Hmm, timezone shouldn't affect the month being between 1 and 12. I know Australia is weird, but there's only 12 months down there right?

If I give you a patch to add some debug can you apply it?

**Comment by Pre10der** [comment]
Sure thing. haha I could say the same about the US :)

I was wondering if the DD was attempting the be inserted into the MM or something similar.
AU format: DD/MM/YYYY
US format: MM/DD/YYYY

Happy to help add some debug.

**Comment by kk7ds** [comment]
Oh, sorry, I missed the "date format" part, and zeroed in on the timezone thing. Yeah, that's probably the issue indeed. The python API will be the same, so it must be the device giving it back in the other format, but I doubt it tells us which it is. Let me think on it for a few...

**Comment by Pre10der** [comment]
No prob! Thanks 👍

**Comment by kk7ds** [comment]
Can you try this:

```
$ python
>>> import datetime
>>> datetime.datetime.now().strftime('%x')
```
...and tell me if it gives you 12/08/2017 or 08/12/2017 in your locale?

**Comment by Pre10der** [comment]
```
pi@HOST:/home/pi# python3
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now().strftime('%x')
'12/08/17'
>>> 
```

**Comment by kk7ds** [comment]
Bummer, python doesn't seem to know that your locale expects the other format. So I guess I'll have to do a flag.

**Comment by kk7ds** [comment]
Okay, here is something to try:

https://gist.github.com/kk7ds/dc92ddf5ee489081ac781d9910d67ee0

In your config.ini, set:

```
[config]
euro_date_format = True
```

(Untested, so if this explodes let me know and I'll test it after dinner)

**Comment by Pre10der** [comment]
Will do.....but my config.ini is not being created (see my other issue). I will manually add it for now and see what I can get going whilst you have dinner :) Enjoy!

**Comment by kk7ds** [comment]
I saw the subject line of that one but haven't looked yet. I think it's most likely that its trying to create config.ini in a place where it can't or you're not expecting. Try passing -f with a path to a known-good place to write it.

**Comment by Pre10der** [comment]
Yeah, I was passing `--config /home/pi/config.ini` and it wasn't creating it. Will keep playing.... -f errors out, so I assume you mean --config

**Comment by kk7ds** [comment]
So the config file will only be written if/when the controller sends a zone name message. All of the units I've used this with send that message, but I wonder if yours doesn't for some reason?

**Comment by Pre10der** [comment]
OK - that's intersting. Mine is sending 'Unknown' for all zones. 
I manually created a config.ini and ensured it was writable. Updated controller.py and it seems to execute ok (no explosions!). Just not entirely sure if it is picking up the config.ini entry as I can't see it noting that anywhere in the debug logs. I am adding some logging lines.
Will config.ini still be read if it does not create it....i.e. Can I use config.ini to manually specify zone names? This will be helpful with my home assistant integration which presently sees them as 'unknown'.

**Comment by kk7ds** [comment]
Yours isn't sending Unknown, that's the default if the code (a) hasn't heard about the name yet from the controller and (b) doesn't find it in the config file. Since yours isn't sending them, and you didn't have a config, it was always sticking with the default.

But regardless, yes, you can set the zone names in the config manually.

So you're wondering if the euro_date_format flag is working, right? Try setting it to False and see if you get the error message I added in the patch. The patch not only adds the config flag, but also replaces the explosion with a more tame error message hinting at the problem.

**Comment by Pre10der** [comment]
I added a log flag and I can see that it is reading the Euro flag from the manually created config.ini. So fix looks good!

This config.ini has however got me intrigued. Could be an issue with my 584E not sending zone names, but I am sure I had it set as per the recommendations (double checked it)....will look again when I get home.

Do you have a fully populated config.ini that I can reference? Would love to see what the construct is.

**Comment by kk7ds** [comment]
I should put one in the tree, but, here's a snip of mine:

```
[config]
max_zone = 5

[email]
fromaddr = security@foo.com
smtphost = imap.foo.com

[zones]
1 = Front Door
2 = Garage Entry
3 = Garage Side
4 = Garage Back
5 = Kitchen
```

There's really not much in there, as it's mostly for doing the zone names (and now, this flag).

Also note that I don't use the email alerts this way anymore, but I think they still work.

**Comment by Pre10der** [comment]
OK great! That's what I needed. I saw the other issue thread on SMTP alerting...might have a play with that at some point. I note your zones are listed from 1....5. Mine reports zones from 0....X. Is it normal for zones to commence with an id of 0?

**Comment by kk7ds** [comment]
Your what reports 0..X? Like, you see zone zero being toggled? Nowhere in any of my reading of the docs have I seen anything about zero origin zone numbering. So maybe that's some other difference. You'll have to try it and let me know if something doesn't work as expected.

**Comment by Pre10der** [comment]
nx584_client reports zones 0...x when I issue a summary option. OK no worries will do. I'll play around with it some more over the weekend. Thanks for your help! Much appreciated.
