### ISSUE TITLE
event_queue.py is missing

### ISSUE THREAD

**Issue by hassan2050** [kk7ds/pynx584#15]
event_queue.py is missing from the code base.

controller.py imports it 'from nx584 import event_queue' but there is no event_queue.py module.

I have also added a systemd configuration. 

Scott

[myfixes.txt](https://github.com/kk7ds/pynx584/files/1776100/myfixes.txt)

**Comment by kk7ds** [comment]
Guh, sorry about that!

**Comment by zipperten** [comment]
Where did that systemd configuration file go, I cant find it int the code base!
