### ISSUE TITLE
is it possible to "receive" notification when the alarm has been triggered or a zone has "chime" (if alarm is not armed)

### ISSUE THREAD

**Issue by yeahman45** [kk7ds/pynx584#23]
is it possible to "receive" notification when the alarm has been triggered or a zone has "chime" (if alarm is not armed)?

I want to send an sms or email when an alarm has been triggered (if system is armed) or there has been a "chime" in a zone (if system is not armed)

**Comment by kk7ds** [comment]
If you're asking whether or not the code as is can do that, then the answer is no. However, the server side has an event stream, which you can dump with the 'events' thing in the client to see. It's semi-immediate notification of events as they happen. Each zone will report when it is faulted, but you'd have to track the armed state of the partition that it's in yourself if you only want to trigger when the system is disarmed.

**Comment by yeahman45** [comment]
even if the system is not armed, a zone will still report when it's faulted (chime in my case) right?

**Comment by kk7ds** [comment]
Yup. I use it for turning on lights when I walk into the house/garage. It's instant enough for that to be quite satisfying such that I never use the light switch.

**Comment by yeahman45** [comment]
cool thx that's what I needed :)

**Comment by kk7ds** [comment]
Cool, so can I close this issue?
