### ISSUE TITLE
Installation on Hassio?

### ISSUE THREAD

**Issue by GaryOkie** [kk7ds/pynx584#24]
The instructions for installing the NX584 component on HASSIO is clear that pynx584 is required, but it doesn't state if this is installed automatically in its own docker.   The instructions for installing pynx584 don't include any reference to installing it as a Hassio add-on.   

I would greatly appreciate any advice on how a Hassio/RPi3 system can run pynx584 when commands such as pip and docker compose for manual installs aren't available (to my knowledge).

**Comment by GaryOkie** [comment]
I just now found this information in a proposed documentation contribution (from @Pre10der): 

> Using pynx584 with Home Assistant:
Pynx584 can be integrated with Home Assistant (or HASSIO) as follows. Nb. If using HASS.IO, you will need to run nx584_server on a seperate device (like a RaspberryPi - illustrated above). 

My question now is - why is a separate physical server required if I'm using HASS.IO?     Is it just that pynx584 needs to be packaged as a separate add-on?    How difficult would that be?

**Comment by kk7ds** [comment]
You don't need a separate physical server (of course) assuming you're running hass on something physically connected to your alarm panel in some way. The nx584 server process has to speak serial to your alarm panel, either via real serial connection or a SoL device. The reason it's separated like this is so you don't *have* to run hass on the same machine as is connected to your alarm panel.

That said, I don't follow hass development and packaging, so I can't really help you with anything related to integration into their packages or docker stuff, other than to say you can pip install nx584 easily if you're rolling something yourself.

**Comment by Pre10der** [comment]
@kk7ds is right its not necessary to run on a seperate host, however in a HASS.IO install (be it on the legacy ResinOS or the newer HASSOS), it isn't a trivial task to add pynx584_server onto the host and get a serial feed from the NX/Reliance panel communicating. These Hass.IO is designed to operate more like an appliance. For this reason, I found it easier to decouple the nx584 server and run it on a seperate RaspPi (in my case, an old 256Mb RPi v1). It is simply acting as the serial to ethernet bridge, as well as run the nx584 server.

**Comment by GaryOkie** [comment]
Thanks to both of you for the clarifications and advice.   I currently have a Vera+ hub connected to the NX584 and am accessing the security system through the Hassio/Vera component.   I was hoping to have a direct connection with fewer moving parts so adding another Pi to the mix doesn't really accomplish that - but it would let me use the Networx Alarm component instead of Vera.    That may very well make it worthwhile to dedicate a small Pi to that task.

**Comment by HansWegman** [comment]
GaryOkie, I am facing the exact same issue, moving from Vera to HA. Did you get it working?

**Comment by GaryOkie** [comment]
Hi Hans,

Yes, I got HASS communicating using pynx584 running on a dedicated Pi 3.   I had to change the security system to use ASCII instead of BINARY. The same serial>USB fttdi adapter worked fine on the Pi.

I also tried to create a pynx584 HA add-on that would run directly on my main HASS Pi4 system, and came very close, but had an unresolved error, so I shelved it for now.   

I added a Zwave-Me USB gizmo to HASS and have migrated all Zwave devices from Vera to HASS.   With the new Zwave-JS integration, that migration went relatively smoothly.

In reality, if all Zwave/Zigbee/Wifi devices are migrated off the Vera to HASS and all that is left is old Vera CADDX/NX584 running, then that should be considered as an alternative to a Pi running pynx584.   The Vera would then be a dedicated device for interfacing with the security system and should be very stable  - and no need to change anything. 

There are also instructions found on the Vera community forum for how to make the Vera entirely local, and not have it ever communicate with the Vera cloud.

**Comment by HansWegman** [comment]
Thanks a million, that did it for me. It was so long ago that I installed the Vera that I forgot about the binary setting.

Still having trouble in the HA side though, the sensors and alarm panel do it show up but got the pi working!


Met warme groet,

Hans Wegman

Verstuurd vanaf mijn iPhone
