### ISSUE TITLE
config.ini location in docker-compose

### ISSUE THREAD

**Issue by danps1** [kk7ds/pynx584#30]
Hi,
I have got this wonderful software running on Docker using docker-compose.
However, I now want to edit the config.ini file, and can't find it. I have used docker exec to bash into the container, and then tried to use find, but no joy. Assuming it hasn't been created, where in the container should I be making it?
Thanks for any help.

**Comment by farberm** [comment]
danps1 - Did you ever determine where the config.ini is located (or should be located)?
