### ISSUE TITLE
can you use a serial port to usb adapter on the raspberry pi?

### ISSUE THREAD

**Issue by yeahman45** [kk7ds/pynx584#31]
Anyone tried a serial port to usb adapter on the raspberry pi?
like this one?
https://www.aliexpress.com/item/1pcs-HL-340-New-USB-to-RS232-COM-Port-Serial-PDA-9-pin-DB9-Adapter-support/32799664407.html

does it work well?

**Comment by Pre10der** [comment]
I personally use one of these on a raspberry pi (v1) with great success: https://tldcpreview.tripplite.com/keyspan-high-speed-usb-to-serial-adapter~USA19HS

**Comment by yeahman45** [comment]
thx ... i was stupid and ordered one with usb to serial male instead of female .. need to order another one now

**Comment by wicadmin** [comment]
> I personally use one of these on a raspberry pi (v1) with great success: https://tldcpreview.tripplite.com/keyspan-high-speed-usb-to-serial-adapter~USA19HS

Shouldn't this be female instead of male?

**Comment by thinkyhead** [comment]
@Pre10der — Do you have any hints or guidance on getting the USA-28X (product ID 0113) working under Raspbian / Pi 400? I'm getting the result "Direct firmware load failed with error -2" followed by "ezusb_ihex_firmware_download - request 'keyspan/usa28xb.fw' failed." I assume it's using some common USB-serial bridge chip, so maybe it can just piggyback on another driver.

…Alternatively, maybe I can wire this Wacom Art-Z 12x12 tablet directly to GPIO as an RS232 serial device. But, if I can use the USB-serial adapter, that is preferred.

**Comment by thinkyhead** [comment]
…Alternatively, maybe I can wire this Wacom Art-Z 12x12 tablet directly to GPIO as an RS232 serial device. But, if I can use the USB-serial adapter, that is preferred.

**Comment by Pre10der** [comment]
@thinkyhead - Interesting, mine is currently running on my original RPi v1 using a lite version of debian (minibian) with an old USA-19HS adapter (https://www.tripplite.com/support/USA19HS). It's been some years since I did this but is still running today! From memory it just required usbutils and it was up and working. Try piggybacking the USA-19hs driver and see how you get on.

**Comment by thinkyhead** [comment]
Thanks for the info. It looks like most kernels are including support for these, so it's possible just inserting a `new_id` entry in the right place will be enough to do the trick. I just need to figure out which one is appropriate, and whether that is indeed enough. I've seen some other tips for setting up an RS232 port on the GPIO header, so I might try the direct-to-serial method anyways as an exercise.
