### ISSUE TITLE
Is it possible to trigger the alarm

### ISSUE THREAD

**Issue by danps1** [kk7ds/pynx584#32]
I have this component working really nicely with the Home Assistant integration - thanks very much for writing it!

I wanted to know if it is possible to extend this to be able to trigger the alarm from pynx584? (and hence from Home Assistant)

The scenario is that my alarm system is only motion sensors, however, as part of my home automation, I have door and window sensors implemented using zwave into HA.

It would be easy to write an automation that would trigger the alarm if my back door was opened while the alarm is armed - if the pynx584 allows this?

Thanks for your help.

**Comment by yknot7** [comment]
After some research there is no way to blast siren from [commands](https://www.drivehq.com/folder/p9084843/1816086207.aspx) 

Here is an inefficient workaround if your system is self monitored:

Setup fire panic button 

> From outside of programming type in * + 8 + Programming Code. You will then be asked for the device number. Type 0 and press #. You will then be asked for the location. Type 23 and #. This is done in segment 1 of location 23. You want to make sure that options 5, 6 and 7 are on. You will know that they are on because you will see the numbers being displayed. If they are not displayed then press the corresponding numbers on the keypad to make them show up. The numbers correspond to the explanations below: 

> 5. On enables audible keypad panic. 

> 6. On enables keypad aux 1 (fire panic). 

> 7. On enables keypad aux 2 (emergency panic). 

> Press * to move to the next segment. That will save the info you just changed. Then press # to exit 

add the following code to the files
api.py  between line 78 and 79
`    elif args.get('cmd') == 'siren':
        CONTROLLER.siren(int(args.get('partition', 1)))`

client.py on line 43
`    def siren(self, partition=1):
        r = self._session.get(
            self._url + '/command',
            params={'cmd': 'siren',
                    'partition': partition})
        return r.status_code == 200`

controller.py on line 481 
For fire siren
`    def siren(self, partition):
        self._queue.append([0x3E, 0x04, partition])`

Or for medical keypad siren
` def arm_exit(self, partition):
        self._queue.append([0x3E, 0x05, partition])`
   
http://yourip:5007/command?cmd=siren&partition=1 will trigger the fire alarm siren or the medical keypad siren depending on what you added to the controller.py!

**Comment by kk7ds** [comment]
I'm going to close this as it's not really a bug, but if you want to get those changes in, please submit a PR.
