### ISSUE TITLE
No license selected

### ISSUE THREAD

**Issue by onkelbeh** [kk7ds/pynx584#36]
Hi again Dan,

first, thanks for your work. I would like to include your **next** integration in my Home Assistant Gentoo overlay, https://github.com/onkelbeh/HomeAssistantRepository/

As you see, I'm already at letter "N" in HA's integrations list :-)

But, you have not published a license, not here, and not on pypi, so I am asking for clarification.
According to Gentoo's license guidelines, it is not allowed to redistribute a package without a license (https://devmanual.gentoo.org/general-concepts/licenses/index.html).

Today, [I added it](https://github.com/onkelbeh/HomeAssistantRepository/commit/3ae09ad63e9022fb94319373dfe2debf36e5398d) with an "all-rights-reserved" tag, this forbids redistribution and usage of gentoo's mirror system.

At the bottom of my [README.md](https://github.com/onkelbeh/HomeAssistantRepository/blob/master/README.md) you can find some (outdated) license stats, perhaps this helps your decision. Thanks a lot in advance.

\B.

**Comment by fabaff** [comment]
Any updates on this, @kk7ds?

**Comment by kk7ds** [comment]
Sorry, I missed the original query. Fixed!
