### ISSUE TITLE
Connection to nx590NE

### ISSUE THREAD

**Issue by pepelillo** [kk7ds/pynx584#39]
Hi all.
I have a nx590NE expansion in a NX9 alarm system. This expansion has automation function over TCP so it seems to report the automation protocol over ip (not sure if tcp or udp) in standard port 9997. I've configured this option in DL900 and when I test putty in this port seems to report some info (characters not readable). Does anybody test this SW in this scenario?
Can you give me some advises to try? I've heard about socat and also I've seen that the server can connect to a ip:port.

**Comment by pepelillo** [comment]
I've tested but appartently it does not work.........
The server connects to remote tcp port but whe using client to test and activation some zone I get
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 0: invalid start byte
It drives me to a different protocol, but it's weird because using socat to the same port I get ascii symbols and after converting to hex seems to match the serial protocol if skipping some symbol �
Ascii:
��t~
DD!�~   �`@���~ ��J��t~ �`@���~ ��J~
DD!�~   �`@���~ ��Z��r~
DD �~   �`@���~ ��J��t~
DD!�~   �`@���~ ��Z��r~
DD ���t~
DD!�~   �`@���~ ��J��r~

Ascii parsed
t~
DD!~   `@~ Jt~ `@~ J~
DD!~   `@~ Zr~
DD ~   `@~ Jt~
DD!~   `@~ Zr~
DD t~
DD!~   `@~ Jr~

Hex:
74 7e 0a 44 44 21 7e 20 20 20 60 40 7e 20 4a 74 7e 20 60 40 7e 20 4a 7e 0a 44 44 21 7e 20 20 20 60 40 7e 20 5a 72 7e 0a 44 44 20 7e 20 20 20 60 40 7e 20 4a 74 7e 0a 44 44 21 7e 20 20 20 60 40 7e 20 5a 72 7e 0a 44 44 20 74 7e 0a 44 44 21 7e 20 20 20 60 40 7e 20 4a 72 7e 0a 0a 0a

Message example:
7e 20 20 20 60 40

Can somebody give a clue?

Thanks

**Comment by choeflake** [comment]
I'm also interested if pynx584 could work with nx590 (serial over TCP).

**Comment by kk7ds** [comment]
> I'm also interested if pynx584 could work with nx590 (serial over TCP).

As noted in the README, you can already use serial over TCP:

```nx584_server --connect 192.168.1.101:23```

the question would be is if whatever your endpoint is supports the ASCII protocol as implemented by this project. If so, it should just work, although it might require some configuration.

**Comment by choeflake** [comment]
> the question would be is if whatever your endpoint is supports the ASCII protocol as implemented by this project. If so, it should just work, although it might require some configuration.

Indeed, that is exactly the question. @pepelillo shows that there is a port, but unsure about the protocol for that port.

**Comment by choeflake** [comment]
At this link https://github.com/sqrammi/caddx/issues/1, @lucioluxx says that it seems the be the same, only binary.

**Comment by pepelillo** [comment]
Confirmed, only Binary, so not usable. I´d like to have pynx584 in binary format as nxgipd (but this one does not support serial over tcp)
