### ISSUE TITLE
TypeError: unicode strings are not supported, please encode to bytes

### ISSUE THREAD

**Issue by mikegwatson** [kk7ds/pynx584#4]
**environment:** NX-8E set to ASCII, Raspberry Pi, Raspian(Jessie), Python 3.4.2, Home Assistant

**command:** nx584_server --serial /dev/ttyUSB1 --baud 38400

**error:** Python exception with error message: 

> TypeError: unicode strings are not supported, please encode to bytes: '\n073B1101020C00026470\r'

**Comment by kk7ds** [comment]
Okay, this was already fixed in 800bb608a99aa1f8d18c32a5492be904cfe301ad but it wasn't in the latest release (0.3). Also, home-assistant was using 0.2 anyway, so it definitely didn't have it.

I just pushed 0.4 to pypi for this and will push an update to homeassistant to get the new dep.
