### ISSUE TITLE
false alarm signals

### ISSUE THREAD

**Issue by nflo21** [kk7ds/pynx584#46]
Hello,

I have installed a caddx NX-8 alarm system with 3 partitions and a NX584 module.
I have connected my RPi3 running home assistant with the NX-8 board via the nx584 module using a usb-to-serial-rs232 adapter.
At the moment i can communicate with the nx-8 alarm system through home assistant buy I have some issues.

The main problem I face is that I can arm the alarm but I cannot disarm it.
In the log file I see the arm activation but there is nothing (no error indication) when i send the disarm command.

Also a second issue I have is that I have included nx584 as a binary sensor in my configuration.yaml file but I cannot see any of my zones, they are not exposed to home assistant.

Can someone help me with the above issues, please?
Thank you in advance.
Nikos

**Comment by Pre10der** [comment]
Are you sure you have configured your NX-584 card options correctly as per [https://github.com/kk7ds/pynx584/wiki/Setting-up-your-NX-alarm-panel](url)?

Not seeing any of your zones may be due to your config.ini file. Check to make sure it is configured as per [https://github.com/kk7ds/pynx584/wiki/Config-Reference](url). In my case, I had to manually create my file before it would detect the zones.

**Comment by nflo21** [comment]
> Are you sure you have configured your NX-584 card options correctly as per [https://github.com/kk7ds/pynx584/wiki/Setting-up-your-NX-alarm-panel](url)?
> 
> Not seeing any of your zones may be due to your config.ini file. Check to make sure it is configured as per [https://github.com/kk7ds/pynx584/wiki/Config-Reference](url). In my case, I had to manually create my file before it would detect the zones.

Thank you for the feedback. 
I have forgotten to activate options 1 & 2 of Feature 3 / Segment 3 of the NX-584 module. Now I can arm and disarm the partitions.
Also, as you suggested, I have manually created the config.ini file and now I can see the zones. 

The new problem I am facing now is that when I start the pynx584 server, my alarm signals handler (a company to which my Caddx NX-8 system is connected via land phone line and GPRS, in order to report the status of my system) calls me and informs me that they have received an alarm signal from my NX-8 system, which is actually a false alarm since the siren in my home is not activated.
Also, the same false alarm signals are received from the alarm signals hander company when I arm my NX-8 system.
When the pynx584 server is not running no false alarm signals are send to the alarm signals hander company.
As I mentioned before the only cases those false alarm signals are send to the alarm signals hander company is when I start the pynx584 server and when I arm the alarm system while pynx584 is running.
Have you ever faced such issue? Do you have any idea why this happens?

**Comment by Pre10der** [comment]
I don’t know why this would be happening as I did not develop the code, however it was for this reason, amongst a few others that I decided to ditch my alarm monitoring company, and defaulted my panel. That allowed me to be in full control, only I knew the master code, and I was able to disperse alarm alerts across a broader group of people in a more controlled manner. How wedded you your monitoring company are you?

**Comment by nflo21** [comment]
> I don’t know why this would be happening as I did not develop the code, however it was for this reason, amongst a few others that I decided to ditch my alarm monitoring company, and defaulted my panel. That allowed me to be in full control, only I knew the master code, and I was able to disperse alarm alerts across a broader group of people in a more controlled manner. How wedded you your monitoring company are you?

I don't have a problem with my monitoring company. I have full control of my alarm system and they only monitoring my alarm signals in order to inform me and/or the police in case of a situation. 
The problem I have now as explained in my previous post is that when I start the pynx584 server and also when I arm (stay or full arm) my NX-8 system, false alarms for a specific zone are generated and send to the monitoring company.
The issue is that they call me and inform me that an alarm was triggered and ask me if there is a situation, although the specific zone is closed and no siren is activated.
I do not know why these false alarms are generated and specifically that they are generated only when pynx584 is started and when I arm my system with the pynx584 running.
When the pynx584 server is off, no false alarms are generated.
I cannot understand why this happens. Do you have any idea about this issue?

**Comment by Pre10der** [comment]
I don't know the answer to this sorry. As a work around, I wonder if it is possible for the monitoring company to distinguish between the false event types that are being flagged, and noting to ignore those specific events?
@kk7ds may know more.

**Comment by nflo21** [comment]
Yesterday, I found out which was the responsible for the false alarm signals. I have a TRIKDIS G16 cellular communicator attached on the NX-8 board. When I unplugged the TRIKDIS and have only my land phone line connected on NX-8 board, no false alarm signals were generated.
What I am looking right now to find out is why the TRIKDIS generates these false alarm signals at the following specific situations:
- when I start the pynx584 server, or
- when I arm the alarm system

If anyone has any idea on this please let me know.
