### ISSUE TITLE
Unable to arm alarm

### ISSUE THREAD

**Issue by cojaxx** [kk7ds/pynx584#47]
Hello,
I can't figure out why my setup is not working. The server starts successfully and I can read data from the alarm panel, but every time I try and arm the alarm it doesn't work. 

Attached are debug logs when I try and arm the panel using the nx584_client arm --partition 1 command.

The other thing I've noticed is that every time the server is started it fails to process message type 10

"2020-09-26 20:03:52,425 controller ERROR Failed to process message type 10"

Any thoughts on what might be happening?

Regards,
Peter

[logs.txt](https://github.com/kk7ds/pynx584/files/5286528/logs.txt)

**Comment by kk7ds** [comment]
Is this still a problem? Your panel has to be configured to allow the arm command, and since you're not passing a PIN it also has to be configured to allow anonymous arming. I'm not sure what message 10 is, I'd have to look it up, but it might be something related to a rejection or PIN request.

**Comment by cojaxx** [comment]
Yeah I never got it working in the end! Ended up removing the system and installing a Inception controller.
Thanks for the reply anyway.
