### ISSUE TITLE
-bash: nx584_server: command not found

### ISSUE THREAD

**Issue by tennisdad** [kk7ds/pynx584#52]
Am trying to install this on a Raspberry Pi with a USB to serial adapter. I have run 
pip install pynx584 
but get:
pi@raspberrypi:~ $ nx584_server --serial /dev/ttyUSB1 --baud 38400
-bash: nx584_server: command not found

Any suggestions?
Thanks!

**Comment by kk7ds** [comment]
It's hard to know without seeing more information. If you ran pip as the pi user (i.e. not with sudo) then the binary is probably installed in ~/.local/bin or something that isn't in your path.

**Comment by tennisdad** [comment]
Thanks. That was the issues. installed with sudo and that fixed it. 
On to next steps then... :)
