### ISSUE TITLE
GE Concord interfaced with Superbus 2000 Rs‐232 Automation Module

### ISSUE THREAD

**Issue by tennisdad** [kk7ds/pynx584#53]
Quick basic question. Will / should this work with a GE Concord GE security system that is interfaced with Superbus 2000 Rs‐232 Automation Module?

Thanks!

**Comment by kk7ds** [comment]
I don't know and it looks like nobody else has chimed in here with an answer either, so I'm going to close this for the time being. If that system speaks the exact same protocol as the NX8 then probably (there are a lot of clones and re-brands), but it not, then ... no.

**Comment by rwa** [comment]
No, but this project based on it should: https://github.com/JasonCarter80/concord232
