### ISSUE TITLE
Arming/Disarming specific partition stopped working after installing home assistant in docker container

### ISSUE THREAD

**Issue by nflo21** [kk7ds/pynx584#57]
Hello,

After changing to home assistant running as a docker container, arming/disarming a specific partition, other than partition 1, stopped working.
I have 3 partitions on my NX-584 system and before that issue I was able to arm either partition 1, or partition 2 or partition 3.
Now, when I am trying to arm partition 2 or 3, partition 1 is armed instead.
Can you please advise, how should i setup pynx584 to work with home assistant docker container ?
Thank you in advance.

**Comment by kk7ds** [comment]
Did you get this resolved? I don't use hass so I can't provide any specific help. It sounds like the add-on in the repo mentioned in #72 might help?

This isn't an issue with pynx584 and nobody else has chimed in to help, so I'd like to close this if possible.

**Comment by nflo21** [comment]
Yes issue is resolve and you can close the thread.
The problem was caused after updating HA in the docker container and the fact that after such update the ssh key was lost.
As soon as, I updated the ssh key for accessing through https my HA instance all commands send to the NX-584 (including arming / disarming commands) were successfuly executed.
Thank you.
