### ISSUE TITLE
Email notifications and alarm triggering

### ISSUE THREAD

**Issue by lumavp** [kk7ds/pynx584#6]
I've installed pynx584 on a raspberry pi and configured the Home Assistant platform. Everything is working fine. 
I've seen in the source code a module that seems to be for email notifications. Is there any documentation on how to configure it? I will like to send an email notification when the alarm is triggered. 

Another feature I'm looking for is to trigger the caddx siren as when a panic button is being pressed. I have z-wave smoke sensors configured in Home Assistant and will like to trigger the  caddx alarm siren when a smoke sensor goes on. Is this something possible?

Many thanks,
Luis.

**Comment by lumavp** [comment]
I've looked into the code and learned about the config.ini file, how to set it up and the different email notifications available.  I'm not a python programmer but it seemed to me as a very complete implementation of all nx584 features and an excellent programming job. I had to introduce a couple of additional lines in mail.py to send mail through gmail.com and all notifications are working fine now. 

In regards to triggering the alarm, I've introduced some code for a panic command replicating the arm command and using the panic police option(0x06). I can trigger now the siren  with  $ nx584_client panic

**Comment by Pre10der** [comment]
@lumavp - Can you provide an example of your config.ini file please? Would love to see an example of this being used in practice.

**Comment by Pre10der** [comment]
@lumavp - Ignore my last as that has now been added to the repo. However could you please share the code changes you have made for mail.py and nx584_client panic so that these could be submitted to the build? These will be useful for others (including myself).
The pynx584 library coupled with Home Assistant can actually allow for a complete replacement of the NX-595E (Comnav) board that is currently in my, and likely many others panels.

**Comment by lumavp** [comment]
Hi,
I need to revisit what I did as I have forgot completely. I'll do when I
get some free time.
Luis.

**Comment by Pre10der** [comment]
Thank you. That would be excellent. Happy to look at the code myself and reverse engineer it if its easier for you just to post up your modified python (assuming you still have them).
