### ISSUE TITLE
Cannot get pynx584 to start on boot

### ISSUE THREAD

**Issue by farberm** [kk7ds/pynx584#60]
I am installing on a raspberry pi4
My install is located at /usr/local/bin

I followed the instructions under Additional pynx584 Documentation (#13)

I then edited the rc.local file (located in /etc) to include the following:

sudo su - pi -c '/usr/local/bin/nx584_server --config /home/pi/config.ini --connect 192.168.2.71:4999 --baudrate 9600 --listen 192.168.2.165 --port 5007 --log /home/pi/nx584.log'

???NB - 192.168.2.165 is the address of the raspberry pi that I am running on - should this be local 127.0.0.1????

When I reboot however nx584 is not running. 

I have to log into the terminal and issue the command from directory /home/pi
~ $ nx584_server --connect 192.168.2.71:4999 --baudrate 9600 ......AND IT WORKS 

Not sure what I am doing wrong?

**Comment by farberm** [comment]
Ok I finally got this to boot by using the docker-compose method to install

Where should the config.ini file be located for docker compose. I looked at the docker-compose-yml file and I have tried to place it in the home/pi without success as well as the home/pi/docker/pynx584 location and edited the docker-compose without success. It does not locate all 30 of my zones

**Comment by kk7ds** [comment]
You'd need to add something to the compose config to pass your config file into the container. That's really a docker/docker-compose question, not related to pynx584.
