### ISSUE TITLE
install on Home assistant OS

### ISSUE THREAD

**Issue by pepelillo** [kk7ds/pynx584#63]
I know this is not an issue with pynx584, but I'm trying to install it on Home Assistant OS supervisor activated, but as is docker based  I have no idea on how to do it, I can install it on every docker used by portainer, but the changes are not persistant). Does anybody guide me to the right direction please?

**Comment by gveloce** [comment]
Hi mate. Just install in on the Linux OS (not inside docker)

**Comment by ivmarkov** [comment]
See also https://github.com/kk7ds/pynx584/issues/72
