### ISSUE TITLE
Partition Support

### ISSUE THREAD

**Issue by raymonvdm** [kk7ds/pynx584#64]
I`m using pynx584 for a long time and i thougt it was working fine, but after a recent restart of the system, i noticed that i was unable to arm/disarm the alarm using HomeAssistant. I`m not quite sure who to blame but maybe both software packages.

When asking status, i sometime get back partion1, sometime partion 4 and sometimes both (seems to be related to the startup of nx485_server) but if i get partion 4 as the first partion HomeAssistant seems to mess it up and wants to follow partion 4 as alarm partion. I`m only using partion 4 as a partion for motion detecting using Alarm PIR/Radars

This is fine 

```
root@mini:/# nx584_client summary
+------+------------------+--------+--------+
| Zone |       Name       | Bypass | Status |
+------+------------------+--------+--------+
|  1   |      Zone 1      |   -    | False  |
|  2   |      Zone 2      |   -    | False  |
|  3   |      Zone 3      |   -    | False  |
|  4   |      Zone 4      |   -    | False  |
|  48  |     Zone 48      |   -    | False  |
+------+------------------+--------+--------+
Partition 1 armed
```
This is not

```
root@mini:/# nx584_client summary
+------+------------------+--------+--------+
| Zone |       Name       | Bypass | Status |
+------+------------------+--------+--------+
|  1   |      Zone 1      |   -    | False  |
|  2   |      Zone 2      |   -    | False  |
|  3   |      Zone 3      |   -    | False  |
|  4   |      Zone 4      |   -    | False  |
|  48  |     Zone 48      |   -    | False  |
+------+------------------+--------+--------+
Partition 4 disarmed
Partition 1 armed

```

**Comment by kk7ds** [comment]
Can you try with the above-referenced commit to see if that helps?

Also, do you have the "Set time" command enabled on your panel? Seeing the first bit of the exchange in the debug log after startup might help.
