### ISSUE TITLE
Update version in HASSOS

### ISSUE THREAD

**Issue by pepelillo** [kk7ds/pynx584#75]
Yes, probably is not the place to ask, but maybe someone can help.
How can update pynx584 in a Home Assistant OS installation?, normally is installed into Homeassistant container.

**Comment by kk7ds** [comment]
Have you seen #72? That said, I don't use HASS myself and updating the version of nx584 used in HASS is really not a question for this forum, so I'm going to close this. I'm sure there are many active HASS people in that community that can help :)
